name: 'malumis '
favicon: null
layout_spectrum: 0.5133653790690005
typography_spectrum: 0.760632110061124
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2dfc5'
    - '#bdb69f'
    - '#868c8d'
    - '#28243c'
    - '#7c6038'
  brandStrength: 0.375
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
