name: 'malumis '
favicon: null
layout_spectrum: 0.5133653790690005
typography_spectrum: 0.760632110061124
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.12194601609371603
  lightness: 0.6609506604727358
  saturation: 0.9567639192100614
  rhythmicContrast: 0.5031874806154519
purpose: []
